project:
  type: website
  output-dir: .

website:
  title: "Emiliano Montalvo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - professional.qmd
      - research.qmd
      - outputs.qmd
      - conferences.qmd
      - education.qmd
      - recommendations.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

