project:
  type: website
  output-dir: .

website:
  title: "Emiliano Montalvo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - outputs.qmd
      - professional.qmd
      - education.qmd
      - recommendations.qmd


format:
  html:
    anchor-sections: false
    theme:
      - solar
      - brand
    css: styles.css
    toc: false

editor: visual
