---
title: "Conferences"
format: html
editor: visual
---

## Conference Presentations

### *Use of Childcare Centers: Impact on the Socioeconomic Level of Households in the Southern Region of Mexico* — 2026

*Research Seminar "Econoseries", Tecnológico de Monterrey.*

### *El Rincón de Siempre: A Proposal for Community Care and Social Participation in Old Age* — 2026

*International Colloquium City, Care, and Aging, Universidad Autónoma del Estado de México.*

### *Shaping the Future with Our Future: A Multi-/Interdisciplinary Approach* — 2025

*Research Seminar, Omicron Delta Epsilon México Beta Chapter, Tecnológico de Monterrey.*

### *Exploring the Role of Coping Mechanisms and Professional Experience in Job Placement Perception* — 2025

*Monterrey International Book Fair, Tecnológico de Monterrey.*

### *The Influence of Daily Conferences Rhetoric on Andrés Manuel López Obrador's Presidential Approval* — 2025

*II Graduate Student Colloquium in Political Science, El Colegio de México; Research Seminar "Econoseries", Tecnológico de Monterrey.*

[▶ Watch Presentation](https://youtu.be/TnNuukrP6Qw?t=10053)
